= CDC Workshop Repository

image:https://badges.gitter.im/cdc-workshop/Lobby.svg[link="https://gitter.im/cdc-workshop/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
image:https://travis-ci.org/ollin/cdc-workshop.svg?branch=master["Build Status", link="https://travis-ci.org/ollin/cdc-workshop"]

== Idea

There is an _address service_ which delivers addresses. This is the *producer*.
In addition there is an _invoice service_ which is a *consumer* of the address service.

== Working with the code

To develop, run and build a JDK 8 is required. The build system is
https://gradle.org/[gradle].
The services are implemented with https://projects.spring.io/spring-boot/[spring boot].

=== Test the code

_cd_ into the directory of your checkout.

To test all services:

[listing]
----
$ ./gradlew test # for linux
----

[listing]
----
$ ./gradlew.bat test # for windows
----

=== Run address-service

[listing]
----
$ ./gradlew :address-service:bootRun
----

TIP: `ctrl^c` ends the running spring boot server

http://localhost:8888/addresses/ delivers the list of all addresses.



=== Run invoice-service

[listing]
----
$ ./gradlew :invoice-service:bootRun
----

http://localhost:7777/invoices/ delivers the list of all invoices.

== Working with the presentation

The link:presentation/src/docs/asciidoc/presentation.adoc[presentation] is written with http://asciidoctor.org/[asciidoctor]

To generate the presentation:

[listing]
----
$ ./gradlew asciidoctor
----

afterwards you can present with a browser (here we are using firefox):

[listing]
----
$ firefox ./presentation/build/asciidoc/html5/presentation.html &
----

